# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.nab.userservice: INFO
server:
  port: 8083
spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  data:
    mongodb:
      #uri: mongodb://admin:admin@localhost:27017
      uri: mongodb://localhost:27017
      database: ProductTrackingService
# ===================================================================
# RabbitMQ properties.
# ===================================================================
  rabbitmq:
    listener:
      simple:
        concurrency: 4
        max-concurrency: 8
    host: localhost
    port: 15672
    username: guest
    password: guest
queue:
  tracking:
    name: productQueue
exchange:
  product-exchange:
    name: product.topic
# ===================================================================
# Application properties.
# Note : 
# Token Expired Time in mins
# ===================================================================
gateway:
  ip: 192.168.43.7