# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    com.nab.registry: DEBUG
server:
  port: 8010
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  security:
    user:
      name: test
      password: test
