# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.nab.userservice: INFO
server:
  port: 8085
spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/OrderMicroservice?createDatabaseIfNotExist=true
    username: root
    password: root
# ===================================================================
# RabbitMQ properties.
# ===================================================================
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
queue:
  order:
    name: orderQueue
  dead-order:
    name: deadOrderQueue
exchange:
  payment-exchange:
    name: payment.topic
# ===================================================================
# Application properties.
# Note : 
# Token Expired Time in mins
# ===================================================================
gateway:
  ip: 192.168.43.7
# ===================================================================
# RabbitMQ properties.
# ===================================================================
spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest